version: '3.0'
services:

  strategos:
    build: .
    container_name: "${STRATEGOS_CONTAINER_NAME}"
    restart: always
    volumes:
      - .:/var/www
    ports:
      - "${STRATEGOS_PORT}:80"
    environment:
      - DB_HOST=strategos_db
      - "DB_USER=${STRATEGOS_DB_USER}"
      - "DB_PASSWORD=${STRATEGOS_DB_PASSWORD}"
      - "DB_NAME=${STRATEGOS_DB_DATABASE}"
    networks:
      - db

  strategos_db:
    image: mariadb:10.3.4
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;'
    container_name: "${STRATEGOS_DB_CONTAINER_NAME}"
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${STRATEGOS_DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${STRATEGOS_DB_DATABASE}"
      - "MYSQL_USER=${STRATEGOS_DB_USER}"
      - "MYSQL_PASSWORD=${STRATEGOS_DB_PASSWORD}"
    networks:
      - db

networks:
  db:
